### ISSUE TITLE
Atari Lynx

### ISSUE THREAD

**Issue by Brodieman** [RetroPie/es-theme-zoid#2]
Love this theme.  Atari Lynx isn't working, it's just white, no images.  Thoughts on a fix?

**Comment by HerbFargus** [comment]
Feel free to submit a PR to add atari lynx.

**Comment by Brodieman** [comment]
It won't let me

**Comment by MacGyverr** [comment]
This issue has been resolved a while back with this commit.
https://github.com/MacGyverr/es-theme-zoid/commit/5396ac200d2947224b70505219b3bb0b030f329b
