### ISSUE TITLE
Various missing system themes

### ISSUE THREAD

**Issue by MacGyverr** [RetroPie/es-theme-zoid#3]
I love this theme but as you know it's missing various systems.

Atari Lynx
Both Wonderswans
VideoPac
Sega SG-1000
Vextrex
Virtual Boy
Game & Watch

Anyway, I am more than willing to make them, can you tell me what font you used on the "gen_art.jpg" screen?  Or could you maybe put one of the raw layered .psd's in the repository so that we can just cut and paste (and see the drop shadow and font settings for) the elements for the missing systems?

Or if you'd like to maintain creative control, can we help out by putting all the needed image elements in a repository to help you to be able create them easily?

**Comment by HerbFargus** [comment]
None of the devs here created this theme. The original creator was on the old retropie forums but I'm unaware of any of their involvement in a long time so I'm sure any pull requests that fit the original design would be welcomed.

**Comment by MacGyverr** [comment]
Ok, here you go, first of many I hope.
https://github.com/MacGyverr/es-theme-zoid/commit/5396ac200d2947224b70505219b3bb0b030f329b

**Comment by MacGyverr** [comment]
Ok, here you go, I updated all the systems I listed above.
https://github.com/RetroPie/es-theme-zoid/pull/4

I will try to go back through all of them later and make ALL the systems match more (controllers on all systems, same color menus, etc)

**Comment by MacGyverr** [comment]
Ok, that should be enough for awhile. Added all the ones I wanted and the missing ones from the original readme.

Go ahead and merge away.

https://github.com/RetroPie/es-theme-zoid/pull/5
