### ISSUE TITLE
Virtual Boy System info

### ISSUE THREAD

**Issue by craciant** [RetroPie/es-theme-zoid#9]
The virtual boy art text says "Atari Lynx"
I would be happy to fix this and add support for more systems if someone could cue me in on what typeface is used.

**Comment by MacGyverr** [comment]
When I did the updates I included a "template folder". It is what I used to make all the new system themes.  It is not really a template as much as a working kludge to get them done but it does the job.  It has the font that seemed the closest in it.   I didn't have any of the original authors templates to work with so this was the best I could come up with.

I fixed it though in this commit, but feel free to expand on anything not right or missing.
https://github.com/MacGyverr/es-theme-zoid/commit/5ef707617f5b07be831fbd391983f37af0fd79f6

**Comment by HerbFargus** [comment]
fixed via #10
